global:
  path: "D:/game/FFXIV/game/sqpack"
  schemaVersion: "latest"

clients:
  en:
    outputDir: "./rawexd/en"
  ja:
    outputDir: "./rawexd/ja"
  de:
    outputDir: "./rawexd/de"
  fr:
    outputDir: "./rawexd/fr"

  cn:
    path: "D:/game/FFXIV/game/sqpack"
    outputDir: "./rawexd/cn"
  ko:
    path: "D:/game/FFXIV_KR/game/sqpack"
    outputDir: "./rawexd/ko"
    # schemaVersion: "latest"
  tc:
    path: "D:/game/FFXIV_TW/game/sqpack"
    outputDir: "./rawexd/tc"
    # schemaVersion: "latest"
