name: Publish Release

on:
  push:
    tags:
      - "v*" # 当推送以 v 开头的标签时触发，例如 v1.0.0

jobs:
  publish:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive # 包含 EXDSchema 等子模块

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Publish Win-x64
        run: |
          dotnet publish -c Release -r win-x64 --self-contained false -p:PublishSingleFile=true -p:DebugType=none -p:DebugSymbols=false --output ./publish

      - name: Zip Release
        shell: pwsh
        run: |
          Compress-Archive -Path ./publish/* -DestinationPath ./XivExdUnpacker-win-x64.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: XivExdUnpacker-win-x64.zip
          generate_release_notes: true
          draft: false
          prerelease: false
